---
- hosts: jellyfin_host
  become: yes
  vars_files:
    - passwd.yml
  vars:
    ansible_become_pass: "{{ my_cluster_sudo_pass }}"
  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400
  - name: Check if a reboot is needed on all servers
    register: reboot_required_file
    stat: path=/var/run/reboot-required get_md5=no
  - name: Reboot the Debian or Ubuntu server
    reboot:
     msg: "Reboot initiated by Ansible due to kernel updates"
     connect_timeout: 5
     reboot_timeout: 300
     pre_reboot_delay: 0
     post_reboot_delay: 30
     test_command: uptime
    when: reboot_required_file.stat.exists
